inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'test/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'Gemfile'

# C: Style/Documentation: Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# C: Style/ClassAndModuleChildren: Use nested module/class definitions instead of compact style.
Style/ClassAndModuleChildren:
  Enabled: false

# C: Style/AsciiComments: Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: false

# C: Metrics/BlockLength: Block has too many lines.
Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.jbuilder'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'config/routes/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

# C: Style/FrozenStringLiteralComment: Missing frozen string literal comment.
Style/FrozenStringLiteralComment:
  Enabled: false

# C: Layout/LineLength: Line is too long.
Layout/LineLength:
  Max: 160
  Exclude:
    - 'spec/**/*'

# C: Metrics/MethodLength: Method has too many lines.
Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

# C: Metrics/AbcSize: Assignment Branch Condition size for expect_space_json is too high.
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

# C: Metrics/ParameterLists: Avoid parameter lists longer than 5 parameters.
Metrics/ParameterLists:
  Max: 6

# C: [Correctable] Style/ConditionalAssignment: Use the return of the conditional for variable assignment and comparison.
Style/ConditionalAssignment:
  Enabled: false

# C: Style/GuardClause: Use a guard clause (*) instead of wrapping the code inside a conditional expression.
Style/GuardClause:
  Enabled: false

# C: [Correctable] Style/BlockComments: Do not use block comments.
Style/BlockComments:
  Enabled: false

# C: Style/OptionalBooleanParameter: Use keyword arguments when defining method with boolean argument.
Style/OptionalBooleanParameter:
  Enabled: false

# C: Naming/AccessorMethodName: Do not prefix writer method names with set_.
Naming/AccessorMethodName:
  Enabled: false

# C: Style/FormatStringToken: Prefer annotated tokens (like %<foo>s) over unannotated tokens (like %s).
Style/FormatStringToken:
  Enabled: false

# C: [Correctable] Style/NumericPredicate: Use xxx.positive?/zero? instead of xxx > 0/== 0.
Style/NumericPredicate:
  Enabled: false
