services:
  db:
    platform: linux/x86_64 # Tips: mysql -> ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
    image: mysql:8.2.0 # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: xyz789
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "mysql"]
      interval: 5s # <- 30s
      timeout: 10s # <- 30s
      retries: 10 # <- 3
  pg:
    image: postgres:16.1-alpine # https://hub.docker.com/_/postgres
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xyz789
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s # <- 30s
      timeout: 10s # <- 30s
      retries: 10 # <- 3
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/workdir
      - /workdir/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - pg
  job:
    build: .
    command: bundle exec rails jobs:work
    volumes:
      - .:/workdir
      - /workdir/node_modules
    depends_on:
      db:
        condition: service_healthy
      pg:
        condition: service_healthy
  jdk:
    build: schemaspy/
    volumes:
      - ./schemaspy:/workdir/schemaspy
      - ./db:/workdir/db
    depends_on:
      - db
      - pg
