require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/customer_users', type: :request do
  # CustomerUser. As you add validations to CustomerUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      CustomerUser.create! valid_attributes
      get customer_users_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      customer_user = CustomerUser.create! valid_attributes
      get customer_user_url(customer_user)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_customer_user_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      customer_user = CustomerUser.create! valid_attributes
      get edit_customer_user_url(customer_user)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new CustomerUser' do
        expect do
          post customer_users_url, params: { customer_user: valid_attributes }
        end.to change(CustomerUser, :count).by(1)
      end

      it 'redirects to the created customer_user' do
        post customer_users_url, params: { customer_user: valid_attributes }
        expect(response).to redirect_to(customer_user_url(CustomerUser.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new CustomerUser' do
        expect do
          post customer_users_url, params: { customer_user: invalid_attributes }
        end.to change(CustomerUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post customer_users_url, params: { customer_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested customer_user' do
        customer_user = CustomerUser.create! valid_attributes
        patch customer_user_url(customer_user), params: { customer_user: new_attributes }
        customer_user.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the customer_user' do
        customer_user = CustomerUser.create! valid_attributes
        patch customer_user_url(customer_user), params: { customer_user: new_attributes }
        customer_user.reload
        expect(response).to redirect_to(customer_user_url(customer_user))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        customer_user = CustomerUser.create! valid_attributes
        patch customer_user_url(customer_user), params: { customer_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested customer_user' do
      customer_user = CustomerUser.create! valid_attributes
      expect do
        delete customer_user_url(customer_user)
      end.to change(CustomerUser, :count).by(-1)
    end

    it 'redirects to the customer_users list' do
      customer_user = CustomerUser.create! valid_attributes
      delete customer_user_url(customer_user)
      expect(response).to redirect_to(customer_users_url)
    end
  end
end
