require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/downloads', type: :request do
  # Download. As you add validations to Download, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Download.create! valid_attributes
      get downloads_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      download = Download.create! valid_attributes
      get download_url(download)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_download_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      download = Download.create! valid_attributes
      get edit_download_url(download)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Download' do
        expect do
          post downloads_url, params: { download: valid_attributes }
        end.to change(Download, :count).by(1)
      end

      it 'redirects to the created download' do
        post downloads_url, params: { download: valid_attributes }
        expect(response).to redirect_to(download_url(Download.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Download' do
        expect do
          post downloads_url, params: { download: invalid_attributes }
        end.to change(Download, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post downloads_url, params: { download: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested download' do
        download = Download.create! valid_attributes
        patch download_url(download), params: { download: new_attributes }
        download.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the download' do
        download = Download.create! valid_attributes
        patch download_url(download), params: { download: new_attributes }
        download.reload
        expect(response).to redirect_to(download_url(download))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        download = Download.create! valid_attributes
        patch download_url(download), params: { download: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested download' do
      download = Download.create! valid_attributes
      expect do
        delete download_url(download)
      end.to change(Download, :count).by(-1)
    end

    it 'redirects to the downloads list' do
      download = Download.create! valid_attributes
      delete download_url(download)
      expect(response).to redirect_to(downloads_url)
    end
  end
end
