require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/infomations', type: :request do
  # Infomation. As you add validations to Infomation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Infomation.create! valid_attributes
      get infomations_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      infomation = Infomation.create! valid_attributes
      get infomation_url(infomation)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_infomation_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      infomation = Infomation.create! valid_attributes
      get edit_infomation_url(infomation)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Infomation' do
        expect do
          post infomations_url, params: { infomation: valid_attributes }
        end.to change(Infomation, :count).by(1)
      end

      it 'redirects to the created infomation' do
        post infomations_url, params: { infomation: valid_attributes }
        expect(response).to redirect_to(infomation_url(Infomation.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Infomation' do
        expect do
          post infomations_url, params: { infomation: invalid_attributes }
        end.to change(Infomation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post infomations_url, params: { infomation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested infomation' do
        infomation = Infomation.create! valid_attributes
        patch infomation_url(infomation), params: { infomation: new_attributes }
        infomation.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the infomation' do
        infomation = Infomation.create! valid_attributes
        patch infomation_url(infomation), params: { infomation: new_attributes }
        infomation.reload
        expect(response).to redirect_to(infomation_url(infomation))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        infomation = Infomation.create! valid_attributes
        patch infomation_url(infomation), params: { infomation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested infomation' do
      infomation = Infomation.create! valid_attributes
      expect do
        delete infomation_url(infomation)
      end.to change(Infomation, :count).by(-1)
    end

    it 'redirects to the infomations list' do
      infomation = Infomation.create! valid_attributes
      delete infomation_url(infomation)
      expect(response).to redirect_to(infomations_url)
    end
  end
end
