# Devise Token Auth
confirmation_success_url_not: '/auth/confirmation_success.html?not'
confirmation_success_url_bad: '/auth/confirmation_success.html?bad'
confirmation_error_url_not: '/auth/confirmation_error.html?not'
confirmation_error_url_bad: '/auth/confirmation_error.html?bad'
unlock_success_url_not: '/auth/unlock_success.html?not'
unlock_success_url_bad: '/auth/unlock_success.html?bad'
unlock_error_url_not: '/auth/unlock_error.html?not'
unlock_error_url_bad: '/auth/unlock_error.html?bad'
reset_password_error_url_not: '/auth/reset_password_error.html?not'
reset_password_error_url_bad: '/auth/reset_password_error.html?bad'

## ユーザー
# メールアドレス確認URLの有効期限（単位：時間）
confirm_within_hours: 24
# パスワード再設定URLの有効期限（単位：時間）
reset_password_within_hours: 24
# アカウントロックの有効期間（単位：時間）
unlock_in_hours: 1
# アカウント削除の猶予期間（単位：日）
destroy_schedule_days: 7
# アカウント削除完了メール送信(true or false)  Tips:「rails user:destroy[false]」をcronで実行（メール送信する場合、夜間は避けた方が良い）
sendmail_destroy_completed: true
# 氏名の最小・最大文字数
user_name_minimum: 1
user_name_maximum: 32

## お知らせ
# 一覧のデフォルト最大表示件数
default_infomations_limit: 25

## スペース
# 一覧のデフォルト最大表示件数
default_spaces_limit: 25

## メンバー
# 一覧のデフォルト最大表示件数
default_members_limit: 25
# 招待の最大件数
create_members_max_count: 100
