cookie_domain: 'base.localhost.test'
base_domain: 'base.localhost.test'
mailer_from:
  name: '%{app_name}'
  email: 'noreply@localhost.test'

## ユーザー
# ユーザー名の最小・最大文字数
user_name_minimum: 1  # Tips: (14+5?)以下 = "admin_user#{n}test"
user_name_maximum: 19 # Tips: (14+5?)以上

## お知らせ
# 新しいお知らせの最大表示件数
new_infomations_limit: 4 # Tips: 高速化の為（4以上、下記の合計値と一致）
test_infomations:
  all_forever_count: 1
  all_future_count: 1
  user_forever_count: 1
  user_future_count: 1
# 一覧のデフォルト最大表示件数
default_infomations_limit: 4 # Tips: 高速化の為（new_infomations_limitと同じ）

## 顧客
# 一覧のデフォルト最大表示件数
default_customers_limit: 3 # Tips: 高速化の為（3以上、下記の合計値と一致）
test_customers_owner: 1
test_customers_admin: 1
test_customers_member: 1
# 顧客コードの最小・最大文字数
customer_code_minimum: 1  # Tips: (12+5?)以下 = "customer#{n}test"
customer_code_maximum: 17 # Tips: (12+5?)以上
# 顧客名の最小・最大文字数
customer_name_minimum: 1  # Tips: (16+5?)以下 = "顧客(#{code})"
customer_name_maximum: 21 # Tips: (16+5?)以上

## メンバー
# 一覧のデフォルト最大表示件数
default_members_limit: 4 # Tips: 高速化の為（4以上、下記の合計値+1）
test_members_owner: 1
test_members_admin: 1
test_members_member: 1

## スペース
# 新しいスペースの最大表示件数
new_spaces_limit: 3 # Tips: 高速化の為
# 一覧のデフォルト最大表示件数
default_spaces_limit: 3 # Tips: 高速化の為
# サブドメインの最小・最大文字数
subdomain_minimum: 1  # Tips: (7+5?)以下 = "myspace#{sort_key}"
subdomain_maximum: 12 # Tips: (7+5?)以上
# スペース名の最小・最大文字数
space_name_minimum: 1  # Tips: (15+5?)以下 = "マイスペース(#{sort_key})"
space_name_maximum: 20 # Tips: (15+5?)以上
